### ISSUE TITLE
Hodnocení úkolu

### ISSUE THREAD

**Issue by lrolecek** [KaterinaProchazkova/PROJEKT-Vizitka#1]
Ahoj.

Vizuálně vypadá vizitka přesně podle zadání, takže tam nemám co vytknout. Ke kódu mám jen drobné připomínky - úkol ti uznávám, nechám na tobě, zda si to chceš opravit nebo ne.

### Stylování img

Obrázek Elišky styluješ přímo přes selektor značky `<img>` - v rámci tohoto úkolu je to naprosto v pohodě, protože na stránce žádný jiný obrázek není, ale přesto bych doporučoval zvyknout si na to, přidávat na obrázky třídy a pak stylovat tyto třídy. Nikdy nevíš, za někdy později nepřibyde na stránce další obrázek, který pravděpodobně už nebudeš chtít mít nastylovaný jako kolečko v rohu vizitky. Viz Jirkova přednáška na konzultaci minulou středu 10.3.

### Odkazy / tlačítka

To stejné platí pro odkazy, ze kterých děláš tlačítka. Styluješ přímo značku `<a>` - v rámci tohoto úkolu si to můžeš dovolit, ale není dobré si na to zvykat. Na jiných stránkách můžeš mít i další odkazy, které nebudeš chtít stylovat jako tlačítka. Lepší je přidat na oba odkazy třeba třídu _.button_ a tu pak stylovat.

Tlačítkům nastavuješ `display: inline-block;` a zároveň `width: 100%`. V tomto případě, protože jsou tlačítka pod sebou, můžeš jim nastavit rovnou jenom `display: block;` - blokové prvky jsou automaticky pod sebou a zabírají celou šířku, kterou mají k dispozici.

## Opravy

Protože ty "chyby" jsou spíš jen doporučení, jak to do budoucna dělat lépe, a nejde o skutečné chyby, tak úkol ti uznávám. Pokud si chceš "nedostatky" sama opravit, tak:

- [x] přidat třídu k `<img>` a v CSS raději stylovat tuto třídu
- [x] přidat třídu k `<a>` a v CSS raději stylovat tuto třídu

Jinak je to bezva :)

**Comment by KaterinaRadochova** [comment]
Ahoj Luďku, 

děkuji za hodnocení a komentář, mám opraveno 😉
Jo jo ve středu jsem hned věděla, že jsem tam ty třídy nedala, trošku jsem spoléhala, že na stránce nic nepřibude, ale určitě je lepší si na to zvykat od začátku. 
U tlačítek, kde jsem měla display: inline-block; a zároveň width: 100%, tak to byla asi nějaká slabá chvilka nebo nevím..

Děkuji. 😊

**Comment by lrolecek** [comment]
Díky za opravy, teď je to super.
